### ISSUE TITLE
Support for pngs.

### ISSUE THREAD

**Issue by Zemurin** [ParadoxGameConverters/oldProvinceMapper#16]

**Comment by IhateTrains** [comment]
From my duplicate issue:

The mapper expects a `provinces.bmp` file in the map directory, but new PDX games use `provinces.png`. This requires converting to BMP, which may lead to a map-staring guy working on an outdated map if he forgets to repeat the process after a game update.

**Comment by IhateTrains** [comment]
This can be closed :)
